export const cards = [
  {
    id: 1,
    title: "Balance",
    amount: "$5,756",
    bgColor: "bg-[linear-gradient(107.38deg,#4C49ED_2.61%,#0A06F4_101.2%)]",
    gradientBottom: true,
    borderTop: false,
    border: false,
    cardColor: "colored",
    cardTag: "hash",
    textColor: true,
  },
  {
    id: 2,
    title: "Balance",
    amount: "$5,756",
    bgColor: "bg-white",
    gradientBottom: false,
    borderTop: true,
    border: true,
    chipColor: "text-gray-400",
    cardColor: "white",
    cardTag: "deephash",
    textColor: false,
  },
  {
    id: 3,
    title: "Balance",
    amount: "$5,756",
    bgColor: "bg-[linear-gradient(107.38deg,#2D60FF_2.61%,#539BFF_101.2%)]",
    gradientBottom: true,
    borderTop: false,
    border: false,
    chipColor: "text-yellow-400",
    cardColor: "colored",
    cardTag: "hash",
    textColor: true,
  },
];
