export const transactionValue = [
  {
    id: 1,
    transactionType: 'expense',
    description: 'Spotify Subscription',
    transactionID: '#123548796',
    type: 'Shopping',
    card: '1234 ****',
    Date: '28 Jan, 12.30 AM',
    amount: '-$2,500',
    download: 'Download',
  },
  {
    id: 2,
    transactionType: 'income',
    description: 'Freepik Sales',
    transactionID: '#123548796',
    type: 'Transfer',
    card: '1234 ****',
    Date: '25 Jan, 10.40 PM',
    amount: '+$750',
    download: 'Download',
  },
  {
    id: 3,
    transactionType: 'expense',
    description: 'Mobile Service',
    transactionID: '#123548796',
    type: 'Service',
    card: '1234 ****',
    Date: '20 Jan, 10.40 PM',
    amount: '-$150',
    download: 'Download',
  },
  {
    id: 4,
    transactionType: 'expense',
    description: 'Wilson',
    transactionID: '#123548796',
    type: 'Transfer',
    card: '1234 ****',
    Date: '15 Jan, 03.29 PM',
    amount: '-$1,050',
    download: 'Download',
  },
  {
    id: 5,
    transactionType: 'income',
    description: 'Emilly',
    transactionID: '#123548796',
    type: 'Transfer',
    card: '1234 ****',
    Date: '14 Jan, 14.40 PM',
    amount: '+$840',
    download: 'Download',
  },
];
