export const transactionValue = [
  {
    id: 1,
    transactionType: 'expense',
    description: 'Spotify Subscription',
    transactionID: '#123548796',
    type: 'Shopping',
    card: '1234 ****',
    Date: '28 Jan, 12.30 AM',
    amount: '-$2,500',
    download: 'Download',
  },
  {
    id: 2,
    transactionType: 'income',
    description: 'Freepik Sales',
    transactionID: '#123548796',
    type: 'Transfer',
    card: '1234 ****',
    Date: '25 Jan, 10.40 PM',
    amount: '+$750',
    download: 'Download',
  },
  {
    id: 3,
    transactionType: 'expense',
    description: 'Mobile Service',
    transactionID: '#123548796',
    type: 'Service',
    card: '1234 ****',
    Date: '20 Jan, 10.40 PM',
    amount: '-$150',
    download: 'Download',
  },
  {
    id: 4,
    transactionType: 'expense',
    description: 'Wilson',
    transactionID: '#123548796',
    type: 'Transfer',
    card: '1234 ****',
    Date: '15 Jan, 03.29 PM',
    amount: '-$1,050',
    download: 'Download',
  },
  {
    id: 5,
    transactionType: 'income',
    description: 'Emilly',
    transactionID: '#123548796',
    type: 'Transfer',
    card: '1234 ****',
    Date: '14 Jan, 14.40 PM',
    amount: '+$840',
    download: 'Download',
  },
  {
    id: 6,
    transactionType: 'expense',
    description: 'Netflix Subscription',
    transactionID: '#123548797',
    type: 'Service',
    card: '1234 ****',
    Date: '13 Jan, 09.15 PM',
    amount: '-$15',
    download: 'Download',
  },
  {
    id: 7,
    transactionType: 'income',
    description: 'John Carter',
    transactionID: '#123548798',
    type: 'Transfer',
    card: '1234 ****',
    Date: '12 Jan, 11.20 AM',
    amount: '+$1,200',
    download: 'Download',
  },
  {
    id: 8,
    transactionType: 'expense',
    description: 'Amazon Purchase',
    transactionID: '#123548799',
    type: 'Shopping',
    card: '1234 ****',
    Date: '11 Jan, 04.10 PM',
    amount: '-$320',
    download: 'Download',
  },
  {
    id: 9,
    transactionType: 'expense',
    description: 'Electricity Bill',
    transactionID: '#123548800',
    type: 'Service',
    card: '1234 ****',
    Date: '10 Jan, 08.45 AM',
    amount: '-$95',
    download: 'Download',
  },
  {
    id: 10,
    transactionType: 'income',
    description: 'Design Project',
    transactionID: '#123548801',
    type: 'Transfer',
    card: '1234 ****',
    Date: '09 Jan, 06.30 PM',
    amount: '+$2,400',
    download: 'Download',
  },
  {
    id: 11,
    transactionType: 'expense',
    description: 'Uber Ride',
    transactionID: '#123548802',
    type: 'Service',
    card: '1234 ****',
    Date: '08 Jan, 02.10 PM',
    amount: '-$25',
    download: 'Download',
  },
  {
    id: 12,
    transactionType: 'income',
    description: 'Sarah Johnson',
    transactionID: '#123548803',
    type: 'Transfer',
    card: '1234 ****',
    Date: '07 Jan, 10.00 AM',
    amount: '+$680',
    download: 'Download',
  },
  {
    id: 13,
    transactionType: 'expense',
    description: 'Apple Store',
    transactionID: '#123548804',
    type: 'Shopping',
    card: '1234 ****',
    Date: '06 Jan, 05.20 PM',
    amount: '-$540',
    download: 'Download',
  },
  {
    id: 14,
    transactionType: 'expense',
    description: 'Gym Membership',
    transactionID: '#123548805',
    type: 'Service',
    card: '1234 ****',
    Date: '05 Jan, 07.30 AM',
    amount: '-$60',
    download: 'Download',
  },
  {
    id: 15,
    transactionType: 'income',
    description: 'Affiliate Earnings',
    transactionID: '#123548806',
    type: 'Transfer',
    card: '1234 ****',
    Date: '04 Jan, 09.50 PM',
    amount: '+$430',
    download: 'Download',
  },
  {
    id: 16,
    transactionType: 'expense',
    description: 'Starbucks',
    transactionID: '#123548807',
    type: 'Service',
    card: '1234 ****',
    Date: '03 Jan, 08.10 AM',
    amount: '-$12',
    download: 'Download',
  },
  {
    id: 17,
    transactionType: 'income',
    description: 'Michael Brown',
    transactionID: '#123548808',
    type: 'Transfer',
    card: '1234 ****',
    Date: '02 Jan, 01.45 PM',
    amount: '+$970',
    download: 'Download',
  },
  {
    id: 18,
    transactionType: 'expense',
    description: 'Ikea Furniture',
    transactionID: '#123548809',
    type: 'Shopping',
    card: '1234 ****',
    Date: '01 Jan, 03.20 PM',
    amount: '-$780',
    download: 'Download',
  },
  {
    id: 19,
    transactionType: 'income',
    description: 'Crypto Profit',
    transactionID: '#123548810',
    type: 'Transfer',
    card: '1234 ****',
    Date: '31 Dec, 11.30 PM',
    amount: '+$1,350',
    download: 'Download',
  },
  {
    id: 20,
    transactionType: 'expense',
    description: 'Adobe Subscription',
    transactionID: '#123548811',
    type: 'Service',
    card: '1234 ****',
    Date: '30 Dec, 09.40 AM',
    amount: '-$30',
    download: 'Download',
  },
];
